### ISSUE TITLE
Reveal commit mismatch

### ISSUE THREAD

**Issue by cherimarie** [girldevelopit/gdi-core-git-github#5]
When trying to initialize and update the Reveal submodule, I ran into an error. The fix I used is here: http://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error. Looks like you just need to make sure the commit that Reveal is referencing has actually been pushed up to the Reveal repo, or that this repo is referencing a commit that actually has been pushed. Thanks!

**Comment by Roenok** [comment]
Thanks! We've moved away from submodules, to minimize confusion
